### PR TITLE
Fix Pagination for all numbers of minecarts

### PR DESCRIPTION
**Pull request by Jibblestein**
Improved math for PageCount calculation, now accounts for all possibilities

### CODE REVIEW

**Comment by Jibblestein** [comment]
Tested to be working for all numbers of minecarts from 1-21, but should work in all scenarios.

**Comment by Glitchfinder** [comment]
This accounts for the first page's nonstandard size, but does not account for the final page having [5 carts listed rather than 4](https://github.com/bwdy/SDVModding/blob/main/MinecartPatcher/ModEntry.cs#L116).  With 11, 15, 19, etc. carts, where a single cart would be listed on the "final" page, that cart instead [replaces the "Next" option](https://github.com/bwdy/SDVModding/blob/main/MinecartPatcher/ModEntry.cs#L131) on the penultimate page and removes the final page entirely.

To account for that, code like this should work:
```
PageCount = (Math.Max(counter - 3, 0) / 4) + 1;
if (Math.Max(counter - 3, 0) % 4 == 0 && PageCount > 1) PageCount -= 1;
```

**Comment by Jibblestein** [comment]
My calculation does account for the last page having 5 carts listed.  I have just tested and confirmed that 5 minecarts are correctly shown on the final page before a new page is added.

I'll try and illustrate the logic which I didn't account for when I suggested the current main version math (which may be confusing you too).

The first page can have up to 6 minecarts if there is only 1 page. So I use:

`if (counter <= 6) PageCount = 1;`

If you add 1 minecart to have 7 minecarts, you would think there would be 6 on first page, and 1 on second page. But due to Next Page replacing one of the destinations on the first page, there are 5 destinations on first page and 2 destinations on the second page.
(There is never a scenario where there is 1 destination on a page).

This continues on for each subsequent page, it will show 5 if it is the last page, but add 1 more minecart and it will move 1 to the next page along with the new minecart and show 2. This is why the following works for all scenarios.

`else PageCount = 1 + (int)Math.Ceiling((((double)counter - 6) / 4));`

The threshold to generate a new page is offset by 6, not 5. You will see 5 destinations on the last page at 10,14,18,etc. (There will be 5 on first page, 5 on last page and 4 destinations for each page in between) 

A new page containing 2 destinations will be made at 11,15,19, etc. 

Let me know if you need more clarification.

**Comment by Glitchfinder** [comment]
Ah, I see what it is. The count is incremented before checking to see if a cart is valid, and so cart ids are one-based rather than zero-based. This threw off my math for pretty obvious reasons. Frankly, that whole function is overdone in a way that dramatically obscures the logic. Considering this function is one of the core components of an open source project, it would likely be better to drop efficiency slightly in favor of clarity:
```
			// Prepare the menu
			LoadData();
			List<Response> responses = new List<Response>();
			List<Response> carts = new List<Response>();
			
			// Acquire a list of all valid minecarts
			foreach (var mc in Minecarts.OrderBy(x => x.Value.DisplayName))
			{
				if (mc.Value.NetworkId != src.NetworkId) continue;
				if (mc.Value.LocationName == l.Name)
				{
					if (RawDistance(mc.Value.LandingPointX, mc.Value.LandingPointY, Game1.player.getTileX(), Game1.player.getTileY()) < 6) continue;
				}
				if (Game1.getLocationFromName(mc.Value.LocationName) == null) continue;
				if (mc.Value.MailCondition != null && !Game1.MasterPlayer.mailReceived.Contains(mc.Value.MailCondition)) continue;
				carts.Add(new Response(mc.Key, mc.Value.DisplayName));
			}
			
			// Get the number of pages
			int PageCount = (int) Math.Ceiling(((double) carts.Count - 1.0) / 4.0);
			// Get the size of the current page
			int pageSize = (page == 0) ? 5 : 4;
			
			// Handle the lack of a "next" option for the final page
			if ((carts.Count - 2) % 4 == 0)
			{
				PageCount -= 1;
				if (page + 1 == PageCount) pageSize += 1;
			}
			
			// Add options to the page
			if (page > 0) responses.Add(new Response("MCP.PaginationMinus", Helper.Translation.Get("previous")));
			
			// Index handling to account for page one having an extra option
			int baseIndex = (page * 4) + ((page == 0) ? 0 : 1);
			
			for (int i = 0; i < pageSize && (i + baseIndex) < carts.Count; i++) {
				// Index handling for lopsided pages
				responses.Add(carts[i + baseIndex]);
			}
				
			if (page < PageCount - 1) responses.Add(new Response("MCP.PaginationPlus", Helper.Translation.Get("next")));
			responses.Add(new Response("Cancel", Game1.content.LoadString("Strings\\Locations:MineCart_Destination_Cancel")));
			
			// Display the page
			LastPage = page;
			Game1.activeClickableMenu = new DialogueBox(src, this, responses);
			Game1.dialogueUp = true;
			Game1.player.CanMove = false;
```

Mind, I do not currently have a functional SDV modding setup in which to test the above code. It is also worth noting that this would remove the need for the finalPage bool to be passed in, as that gets calculated as necessary on the fly.

**Comment by Jibblestein** [comment]
Yeah it really did take a while for me to get my head around it.

However, I would refrain from rewriting the whole function as it works perfectly fine with the changes in this pull request.
It may be worth discussing with bwdy or making your own pull request for your suggestions.

**Comment by Glitchfinder** [comment]
If I had a viable SDV setup at the moment, I'd have committed it directly to this repository. As it stands, this is going to wait for bwdy to free up and look over.

**Pull request closed without merging**
